### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by jodischneider** [zuphilip/zotero-open-citations#2]
The README should ideally include installation instructions. Here are some sample instructions from http://zotfile.com/#how-to-install--set-up-zotfile 

"Install ZotFile

For Zotero 5, first download the extension file (follow the download link above, click on the .xpi file for the most recent release). Now start Zotero 5 and go to “Tool -> Add-ons -> Tools for all Add-ons (the small, drop-down wheel in the top right corner) -> Install Add-on From File” and select the downloaded .xpi file."

**Comment by zuphilip** [comment]
The README does already include installation instructions: https://github.com/zuphilip/zotero-open-citations/blob/master/README.md#installation

Let me know, whether they are not where you expect them to be or how we can make them more findable. The wording itself is quite similar to what you linked, but I am open for better suggestions.

**Comment by zuphilip** [comment]
Feel free to open this issue again @jodischneider if you want to continue to discuss it.
