### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by atanasj** [zuphilip/zotero-open-citations#20]
Hi, 

Just installed this plugin and it does not work. 

```
macOS 10.14 (Mojave)
Zotero 5.0.57
Zotero Open Citations 0.3.0
```
When I select one or multiple Zotero items, right click and `Check for Open Citations on...` > `OpenCitations COCI` nothing happens. 

I was expecting to have the citations imported as per the `readme`. 

Not sure if I have missed something. Any help would be greatly appreciated. 

Thanks, 
Atanas.

**Comment by zuphilip** [comment]
It is important that you select item(s) with DOI. Can try with the item added by the DOI `10.1016/j.bpj.2011.11.4028`? If the problem still exists then please look into `Help` > `Report Errors...` for more information about what the problems might be.

**Comment by atanasj** [comment]
I have tried this, but still does not work. I have gone to the `Help` > `Report Errors...` but I cannot see anything that indicates issues related to the `zotero-open-citations` add-on. Should I be looking for anything specific?

**Comment by zuphilip** [comment]
Oh, and try to click on one of the other options in the addon menue, e.g. WikiCite. Do you see the alert box `TODO code for checking Wikicite...`?

**Comment by atanasj** [comment]
Got it... The default was 3 but the line was blank, so I guess nothing happened. I added a number and it seems to work now as expected. Thanks for your help and a handy add-on.

**Comment by zuphilip** [comment]
Good that it works now!

Also I don't see why this was a problem in the first-hand. Because if the value is not set, then it should choose `3` by default: https://github.com/zuphilip/zotero-open-citations/blob/05efede7c5ff18038bac08a74dad1faae02317e6/chrome/content/zoteroopencitations.js#L8
