### ISSUE TITLE
please add a specific LICENSE

### ISSUE THREAD

**Issue by egonw** [zuphilip/zotero-open-citations#3]

**Comment by egonw** [comment]
BTW, thanks for doing this. I like where this is going... I think it will be very useful to just be able to click an article citing the article for which the data is given to easily add it to one's Zotero collection.

**Comment by zuphilip** [comment]
I am not sure that I understand  your comment completely:

> I think it will be very useful to just be able to click

Do you mean click in the newly created note?

> an article citing the article for which the data is given

So, you want to click on one DOI of the citations for the original article. Is that correct?

> to easily add it to one's Zotero collection.


BTW I am finishing now a commit with will additionally add the three most recent citations to Zotero. This might go in the direction you imagine. Anyway it is good for demonstrating the possibilities.

**Comment by egonw** [comment]
Yes, click in the newly created not, and when clicking a DOI in that note, it would go to that paper in my Zotero collection or (suggest to) create a new entry for the DOI. I would not want them to be added automatically, tho.

It would also be really cool if Zotero could do more with those citations, like allow me to annotated them with CiTO terms ("uses method in" or "disputes", ... see [this](https://sparontologies.github.io/cito/current/cito.html))

**Comment by zuphilip** [comment]
Ah, that is interesting. Would you mind to copy the last comment as a new issue (maybe two issues for both ideas?) to discuss further?

**Comment by egonw** [comment]
Done:

* citation as first class entity in Zotero https://github.com/zuphilip/zotero-open-citations/issues/5
* function to bookmark listed articles citing the article https://github.com/zuphilip/zotero-open-citations/issues/6
* `crontab`-like feature that updates a note at regular interval https://github.com/zuphilip/zotero-open-citations/issues/7
