### ISSUE TITLE
Search for matches for retrieved citations within the user's library

### ISSUE THREAD

**Issue by zuphilip** [zuphilip/zotero-open-citations#9]
After citations are retrieved from OC search for matches within the user's library. For example from 100 citations of an article I already have 2 of them in my library, for which I can then easily receive more information like title and authors. Moreover, it could be indicated in which collections these matched articles are found.

**Comment by zuphilip** [comment]
Maybe also add also a zotero link of the form `zotero://select/items/1_RJX66R62`. However, this seems to not work currently...

**Comment by HughP** [comment]
![screenshot from 2018-09-25 09-14-33](https://user-images.githubusercontent.com/40230/46027780-864a0400-c0a3-11e8-814e-7f4c450da771.png)

Am I making a correct assumption that the "related item" button and following screen is supposed to manually allow what the OP is asking for automation on?

**Comment by zuphilip** [comment]
Also it seems possible to add these items as related items to the note, I wouldn't do that, because the cited-by items are already related to the item itself. However, what I meant was to add in the note itself a special zotero link. I will include this in the next version.

**Comment by zuphilip** [comment]
Realized in version 0.3.0
